// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDENf_jD6laZWqPX-I9dVJJ77xlGijlG3s',
    appId: '1:175640675832:web:e8a9613e2e651c83a8c20d',
    messagingSenderId: '175640675832',
    projectId: 'tarefasapp-28219',
    authDomain: 'tarefasapp-28219.firebaseapp.com',
    storageBucket: 'tarefasapp-28219.firebasestorage.app',
    measurementId: 'G-W1GGS0X8CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOTd4h_J8iHsZ9hw8DIMNzYbcfpzES1Ck',
    appId: '1:175640675832:android:dc44efc5169c1fe2a8c20d',
    messagingSenderId: '175640675832',
    projectId: 'tarefasapp-28219',
    storageBucket: 'tarefasapp-28219.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAohkOiNgRCbskk_24i6ZRjchWlH6LdZs',
    appId: '1:175640675832:ios:de88e608ea9766b1a8c20d',
    messagingSenderId: '175640675832',
    projectId: 'tarefasapp-28219',
    storageBucket: 'tarefasapp-28219.firebasestorage.app',
    iosBundleId: 'com.example.tarefasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAohkOiNgRCbskk_24i6ZRjchWlH6LdZs',
    appId: '1:175640675832:ios:de88e608ea9766b1a8c20d',
    messagingSenderId: '175640675832',
    projectId: 'tarefasapp-28219',
    storageBucket: 'tarefasapp-28219.firebasestorage.app',
    iosBundleId: 'com.example.tarefasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDENf_jD6laZWqPX-I9dVJJ77xlGijlG3s',
    appId: '1:175640675832:web:f73d39747dcb80eea8c20d',
    messagingSenderId: '175640675832',
    projectId: 'tarefasapp-28219',
    authDomain: 'tarefasapp-28219.firebaseapp.com',
    storageBucket: 'tarefasapp-28219.firebasestorage.app',
    measurementId: 'G-ZEHDYH0D0J',
  );
}
